"""Veracity Platform API proxy helpers (framework-agnostic).

The SPA generated by the **veracity-auth-ui** skill calls the BFF at fixed, versioned
paths (see its ``src/api/veracity.ts`` and the Vite proxy in ``vite.config.ts``):

    GET /api/v1/veracity/v3/services         -> the user's Veracity services (V3)
    GET /api/v1/veracity/v3/policy/validate   -> Veracity-wide policy/subscription check (V3)
    GET /api/v1/veracity/v4/me/applications   -> the user's licensed applications (V4)
    GET /api/v1/veracity/v4/policy/validate   -> policy/subscription check for the configured service (V4)

A project integrates **either** V3 **or** V4 (the user's choice), so generate only the proxy
helpers + routes for the chosen version and drop the other. The two ``policy/validate`` helpers
both validate the signed-in user's policies, but differ in scope: V4 is **service-specific** and
needs ``Settings.service_id`` (``SERVICE_ID``), while V3 validates the user's Veracity-wide
policies and needs **no** service id.

Each web adapter (FastAPI / Flask / Django) exposes exactly those routes and delegates
here. The mount prefix mirrors the .NET skill's versioned group ``/api/v{version}`` and
the frontend's expectations, so the paths line up with **no** frontend changes.

Calls are made *as the signed-in user* using the access token the BFF stored in the
session at login. Because the login request includes the Veracity API scope
(``Settings.login_scopes``), that token is already scoped for ``api.veracity.com`` — the
same posture as Microsoft.Identity.Web in the .NET skill — so it is used directly, with
no on-behalf-of exchange (Azure AD B2C does not reliably support OBO). The
``Ocp-Apim-Subscription-Key`` header is attached by
:class:`veracity_core.apiclient.VeracityAuth`.
"""

from __future__ import annotations

from urllib.parse import quote, urlsplit

import httpx

from veracity_core.apiclient import make_v3_client, make_v4_client
from veracity_core.obo import TokenProvider
from veracity_core.settings import Settings

# Mount prefix the veracity-auth-ui SPA calls. Matches the .NET `/api/v{version}` group
# and the frontend's `/api/v1/veracity/...` fetch paths.
VERACITY_API_MOUNT = "/api/v1/veracity"


class VeracityApiError(RuntimeError):
    """Upstream Veracity API failure, carrying the HTTP status for the adapter to relay."""

    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


def _static_token_provider(token: str) -> TokenProvider:
    """A provider that returns the already-acquired user access token as-is."""
    return lambda: token


def _get_json(client: httpx.Client, path: str):
    try:
        with client as c:
            resp = c.get(path)
            resp.raise_for_status()
            return resp.json()
    except httpx.HTTPStatusError as exc:
        # Relay the upstream status (401/403/404/406/5xx) so the SPA degrades gracefully.
        raise VeracityApiError(exc.response.status_code, exc.response.text) from exc
    except httpx.HTTPError as exc:
        raise VeracityApiError(502, str(exc)) from exc


def get_my_services(settings: Settings, user_access_token: str):
    """V3: the services the current user can access (``GET /my/services``)."""
    client = make_v3_client(settings, _static_token_provider(user_access_token))
    return _get_json(client, "/my/services")


def get_my_applications(settings: Settings, user_access_token: str):
    """V4: the applications licensed to the current user (``GET /me/applications``)."""
    client = make_v4_client(settings, _static_token_provider(user_access_token))
    return _get_json(client, "/me/applications")


def _sanitize_policy_redirect(candidate: object) -> str | None:
    """Constrain a policy redirect candidate to a well-formed absolute ``https`` URL, else ``None``.

    The value comes from the Veracity V3/V4 policy-validation response — trusted upstream content
    reached server-side through the origin allow-list in the API client (authenticated +
    subscription-keyed), **not** caller-supplied free text. This is only a minimal sanity net that
    ensures a malformed or non-``https`` value can never flow through to a client-side redirect.
    """
    if not isinstance(candidate, str) or not candidate.strip():
        return None
    value = candidate.strip()
    parts = urlsplit(value)
    if parts.scheme == "https" and parts.netloc:
        return value
    return None


def _parse_policy_redirect(resp: httpx.Response) -> str | None:
    """Extract the policy-acceptance URL from a response body (``url``/``redirectUrl``/``information``).

    The extracted value is trusted upstream content (see :func:`_sanitize_policy_redirect`) but is
    still constrained to a well-formed absolute ``https`` URL before it is surfaced to the client.
    """
    try:
        body = resp.json()
    except ValueError:
        return None
    if isinstance(body, dict):
        return _sanitize_policy_redirect(
            body.get("url") or body.get("redirectUrl") or body.get("information")
        )
    return None


def _require_service_id(settings: Settings) -> str:
    """The Veracity service this app is connected to; required only by the V4 policy check."""
    if not settings.service_id:
        raise VeracityApiError(500, "Veracity service ID (SERVICE_ID) is not configured.")
    return settings.service_id


def _policy_result(resp: httpx.Response, *, redirect_on_403: bool = False) -> dict:
    """Translate a policy-validation response into ``{compliant, redirectUrl}``.

    A ``2xx`` (V4 ``200`` / V3 ``204``) means compliant; a ``406`` means the user must accept a
    policy or lacks a subscription and should be redirected to ``redirectUrl``. When
    ``redirect_on_403`` is set, a ``403`` carrying a redirect URL in its error detail is treated the
    same as a ``406`` (surfaced as non-compliant with a ``redirectUrl``) so the client can redirect
    the user; a ``403`` without a redirect URL remains a genuine authorization failure. Anything
    else is surfaced as a :class:`VeracityApiError`.
    """
    if resp.status_code == 406:
        return {"compliant": False, "redirectUrl": _parse_policy_redirect(resp)}
    if redirect_on_403 and resp.status_code == 403:
        redirect_url = _parse_policy_redirect(resp)
        if redirect_url:
            return {"compliant": False, "redirectUrl": redirect_url}
    if resp.is_success:
        return {"compliant": True, "redirectUrl": None}
    raise VeracityApiError(resp.status_code, resp.text)


def validate_policy_v4(settings: Settings, user_access_token: str, return_url: str) -> dict:
    """V4: validate the signed-in user's policies for the configured service.

    The service (application) id comes from configuration (``Settings.service_id``) — the Veracity service
    this app is connected to — **not** from the request, so callers cannot validate an arbitrary
    application. Calls ``POST /me/policy-verifications/{serviceId}?return-url=...``.

    Returns ``{"compliant": True, "redirectUrl": None}`` when the user is compliant, or
    ``{"compliant": False, "redirectUrl": <url>}`` when the API responds ``406`` (or ``403`` with a
    redirect URL in its error detail). A ``403`` without a redirect URL, a missing ``service_id``,
    or any other upstream failure raises :class:`VeracityApiError`.
    """
    service_id = _require_service_id(settings)
    client = make_v4_client(settings, _static_token_provider(user_access_token))
    path = f"/me/policy-verifications/{quote(service_id, safe='')}"
    try:
        with client as c:
            resp = c.post(path, params={"return-url": return_url})
    except httpx.HTTPError as exc:
        raise VeracityApiError(502, str(exc)) from exc
    return _policy_result(resp, redirect_on_403=True)


def validate_policy_v3(settings: Settings, user_access_token: str, return_url: str) -> dict:
    """V3: validate the signed-in user's policies (Veracity-wide, not service-specific).

    The return URL is passed via the ``returnUrl`` header (as the V3 Policy
    Service expects). Success is ``204``; ``406`` yields ``{compliant: False, redirectUrl}``. Any
    other failure raises :class:`VeracityApiError`.
    """
    client = make_v3_client(settings, _static_token_provider(user_access_token))
    path = "/my/policies/validate()"
    try:
        with client as c:
            resp = c.get(path, headers={"returnUrl": return_url})
    except httpx.HTTPError as exc:
        raise VeracityApiError(502, str(exc)) from exc
    return _policy_result(resp)

